// Shop Page
export const GET_THELOAI_NAME = "GET_THELOAI_NAME";
export const GET_NUOCSX_NAME = "GET_NUOCSX_NAME";
export const GET_TACGIA_NAME = "GET_TACGIA_NAME";
export const GET_DISPLAY_SANPHAM = "GET_DISPLAY_SANPHAM";
export const SET_DISPLAY_DEFAULT = "SET_DISPLAY_DEFAULT";

// Filter
export const SET_FILTER_SHOW = "SET_FILTER_SHOW";
export const SET_FILTER_SORT = "SET_FILTER_SORT";
export const FILTER_BY_TACGIA = "FILTER_BY_TACGIA";
export const FILTER_BY_NUOCSX = "FILTER_BY_NUOCSX";
export const FILTER_BY_THELOAI = "FILTER_BY_THELOAI";
export const FILTER_BY_RATING = "FILTER_BY_RATING";

// Pagination
export const GET_PAGINATION = "GET_PAGINATION";
export const HANDLE_PAGINATE = "HANDLE_PAGINATE";

// Product Page
export const GET_DETAIL_SANPHAM = "GET_DETAIL_SANPHAM";
export const SET_FILTER_SHOW_REVIEW = "SET_FILTER_SHOW_REVIEW";
export const SET_FILTER_SORT_REVIEW = "SET_FILTER_SORT_REVIEW";
export const SET_DEFAULT_REVIEW = "SET_DEFAULT_REVIEW";
// Cart
export const SET_CART_QUANTITY = "SET_CART_QUANTITY";
//quan ly
export const GET_NHANVIEN = "GET_NHANVIEN";
export const GET_KHACHHANG = "GET_KHACHHANG";
export const GET_DSTAIKHOAN = "GET_DSTAIKHOAN";
export const GET_DSTAIKHOANMETA = 'GET_DSTAIKHOANMETA';
export const GET_FILTERDSTAIKHOANLIMIT = 'GET_FILTERDSTAIKHOANLIMIT';
export const GET_FILTERDSTAIKHOANPAGE = 'GET_FILTERDSTAIKHOANPAGE';
export const GET_GIAMGIA = "GET_GIAMGIA";
export const GET_CTGG = "GET_CTGG";
export const GET_NHANVIENMETA = "GET_NHANVIENMETA";
export const GET_FILTERNHANVIENPAGE = 'GET_FILTERNHANVIENPAGE';
export const GET_FILTERNHANVIENLIMIT = 'GET_FILTERNHANVIENLIMIT';
export const GET_KHACHHANGMETA = "GET_KHACHHANGMETA";
export const GET_FILTERKHACHHANGPAGE = 'GET_FILTERKHACHHANGPAGE';
export const GET_FILTERKHACHHANGLIMIT = 'GET_FILTERKHACHHANGLIMIT';
export const GET_SANPHAM = 'GET_SANPHAM';
export const GET_SANPHAMMETA = 'GET_SANPHAMMETA';
export const GET_FILTERSANPHAMLIMIT = 'GET_FILTERSANPHAMLIMIT';
export const GET_FILTERSANPHAMPAGE = 'GET_FILTERSANPHAMPAGE';
export const GET_PHIEUNHAP = 'GET_PHIEUNHAP';
export const GET_PHIEUNHAPMETA = 'GET_PHIEUNHAPMETA';
export const GET_FILTERPHIEUNHAPLIMIT = 'GET_FILTERPHIEUNHAPLIMIT';
export const GET_FILTERPHIEUNHAPPAGE = 'GET_FILTERPHIEUNHAPPAGE';
export const GET_CTPN = 'GET_CTPN';
export const GET_DONDATHANG = 'GET_DONDATHANG';
export const GET_DONDATHANGMETA = 'GET_DONDATHANGMETA';
export const GET_FILTERDONDATHANGLIMIT = 'GET_FILTERDONDATHANGLIMIT';
export const GET_FILTERDONDATHANGPAGE = 'GET_FILTERDONDATHANGPAGE';
export const GET_FILTERDONDATHANGLINK = 'GET_FILTERDONDATHANGLINK';
export const GET_USERDDH = 'GET_USERDDH';
export const SET_FILTERUSERDDHLINK = 'SET_FILTERUSERDDHLINK';
export const GET_CTDDH = 'GET_CTDDH';
export const GET_USERID = 'GET_USERID';
export const GET_QUYEN_NAME = 'GET_QUYEN_NAME';
export const GET_TACGIA = 'GET_TACGIA';
export const GET_TACGIAMETA = 'GET_TACGIAMETA';
export const GET_FILTERTACGIALIMIT = 'GET_FILTERTACGIALIMIT';
export const GET_FILTERTACGIAPAGE = 'GET_FILTERTACGIAPAGE';
export const GET_NUOC = 'GET_NUOC';
export const GET_NUOCMETA = 'GET_NUOCMETA';
export const GET_FILTERNUOCLIMIT = 'GET_FILTERNUOCLIMIT';
export const GET_FILTERNUOCPAGE = 'GET_FILTERNUOCPAGE';
export const GET_REVIEW = 'GET_REVIEW';
export const GET_REVIEWMETA = 'GET_REVIEWMETA';
export const GET_FILTERGET_REVIEWLIMIT = 'GET_FILTERGET_REVIEWLIMIT';
export const GET_FILTERGET_REVIEWPAGE = 'GET_FILTERGET_REVIEWPAGE';